feat: restructured caching.
edx/commerce-coordinator pull request #114
Opened 2023-08-25 14:01 UTC by HammadAhmadWaqas

**Description:** Describe in a couple of sentences what this PR adds

**JIRA:** Link to JIRA ticket

**Dependencies:** dependencies on other outstanding PRs, issues, etc. 

**Merge deadline:** List merge deadline (if any)

**Installation instructions:** List any non-trivial installation 
instructions.

**Testing instructions:**

1. Open page A
2. Do thing B
3. Expect C to happen
4. If D happened instead - check failed.

**Reviewers:**
- [ ] tag reviewer 
- [ ] tag reviewer 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.

2023-08-25 15:15 UTC, HammadAhmadWaqas commented on commerce_coordinator/apps/core/cache.py
> +def set_payment_processing_cache(payment):
Created Utils for setting cache and getting cache in the core app.

2023-08-25 15:16 UTC, HammadAhmadWaqas commented on commerce_coordinator/apps/core/cache.py
> +    cached_payment_serializer = CachedPaymentSerializer(data=payment)
Added CachedPaymentSerializer in all our caches to make sure caches are consistent

2023-08-25 15:18 UTC, HammadAhmadWaqas commented on commerce_coordinator/apps/frontend_app_payment/filters.py
> -
Moved all caching logic in the core app. Instead of calling it from Filter, now calling it from view. This change made this filter reusable.

2023-08-25 15:18 UTC, HammadAhmadWaqas commented on commerce_coordinator/apps/frontend_app_payment/filters.py
> -                        'Unable to cache Payment data in Processing state')
Moved this PROCESSING cache logic in `MarkTitanPaymentPending`

2023-08-25 21:32 UTC, mzeshanarif requested changes
Thank you @HammadAhmadWaqas for restructuring cache. 👏 
However, Here are a few things that we can do to improve the reusability. Could you please look into the suggestions.

2023-08-25 21:32 UTC, mzeshanarif commented on commerce_coordinator/apps/core/cache.py
> +    return None
How about if we move the common functionality to another method and reuse that method?

```suggestion
def get_payment_cache(payment_state_cache_key):
    """
    Utility for getting cache for specified payment state cache key
    """
    cached_response = TieredCache.get_cached_response(payment_state_cache_key)
    if cached_response.is_found:
        cached_payment_serializer = CachedPaymentSerializer(data=cached_response.value)
        cached_payment_serializer.is_valid(raise_exception=True)
        return cached_payment_serializer.data
    return None


def get_payment_paid_cache(payment_number):
    """
    Utility for getting cache for the payment number from PROCESSING Cache.
    """
    payment_state_paid_cache_key = get_paid_payment_state_cache_key(payment_number)
    return get_payment_cache(payment_state_paid_cache_key)


def get_payment_processing_cache(payment_number):
    """
    Utility for getting cache for the payment number from PAID Cache.
    """
    payment_state_processing_cache_key = get_processing_payment_state_cache_key(payment_number)
    return get_payment_cache(payment_state_processing_cache_key)
```

2023-08-25 21:32 UTC, mzeshanarif commented on commerce_coordinator/apps/core/tests/test_cache.py
> +        self.assertEqual(cached_payment, self.payment)
How about writing separate unit tests for each cache method instead of testing all of three methods/units in same test method?

2023-08-26 12:39 UTC, HammadAhmadWaqas commented
@mzeshanarif Thank you for reviewing the pull request.

Actually, all these methods are related to each other. So it was making sense to test them together. That is why I was thinking of shifting the whole payment cache logic in a class. As caching refactoring was not part of this ticket I was avoiding scope creep as much as possible. Now you have mentioned these things as well, I could not resist and refactored it during my weekend.

Please have a look.

2023-08-28 12:58 UTC, pshiu approved these changes
Really appreciate this refactor, Hammad!

2023-08-28 14:33 UTC, mzeshanarif approved these changes
LGTM 👍

2023-08-28 14:43 UTC, merged