feat: Added unittest to test_views.py
edx/commerce-coordinator pull request #160
Opened 2024-01-26 15:27 UTC by MushtaqRossier

**Description**: Added missing unittest from SONIC-123 and minor changes

**JIRA**: [SONIC-251](https://2u-internal.atlassian.net/browse/SONIC-251)

2024-01-29 12:32 UTC, aht007 requested changes
Not a full review rn, will definitely take look later today. Requested a change.

2024-01-29 12:32 UTC, aht007 commented on commerce_coordinator/settings/base.py
>  ENTERPRISE_USER_CACHE_TIMEOUT = 600  # Value is in seconds
Can we remove the unused `SYSTEM_ENTERPRISE_LEARNER_ROLE` and `ENTERPRISE_USER_CACHE_TIMEOUT`

2024-01-29 13:04 UTC, shafqatfarhan commented on commerce_coordinator/apps/lms/tests/test_views.py
> +        )
```suggestion
        mock_logger.exception.assert_called_once_with(
            '[get_product_variant_by_course_run] Failed to get CT course for course_run: '
            'course-v1:MichiganX+InjuryPreventionX+1T2021 with exception: Error in CT search'
        )
        mock_ct_client.reset_mock(return_value=True, side_effect=True)
```

2024-01-29 13:05 UTC, shafqatfarhan commented on commerce_coordinator/apps/lms/tests/test_views.py
> +            # breakpoint()
Please remove this comment.

2024-01-29 13:07 UTC, shafqatfarhan approved these changes
Approved with a couple of improvement comments.

2024-01-30 09:53 UTC, aht007 approved these changes
LGTM

2024-01-30 12:08 UTC, merged