feat: Endpoint for 'sanctioned' order message
edx/commerce-coordinator pull request #162
Opened 2024-01-31 12:03 UTC by JadeyOlivier

### **WIP**

### Description
Added a view to coordinator for the AWS Eventbridge API destination to point to when receiving a Commercetools subscription message to sanction an order. 

### JIRA
https://2u-internal.atlassian.net/browse/SONIC-165

2024-01-31 12:28 UTC, grmartin approved these changes

2024-01-31 12:28 UTC, grmartin commented on commerce_coordinator/apps/commercetools/urls.py
>      path('fulfill', OrderFulfillView.as_view(), name='fulfill'),
```suggestion
    # EventBridge / CloudWatch Endpoints
    path('fulfill', OrderFulfillView.as_view(), name='fulfill'),
```

2024-01-31 12:28 UTC, grmartin commented on commerce_coordinator/apps/commercetools/views.py
> +    authentication_classes = [] #TODO: Update this with OAuth authentication
If you make this an empty list there are no ayth classes... and thus it cant be hit... (given its permissions_classes requirements)
```suggestion
    # authentication_classes = [] # TODO: Update this with OAuth authentication
```

2024-01-31 13:21 UTC, grmartin requested changes

2024-01-31 13:21 UTC, grmartin commented on commerce_coordinator/apps/commercetools/views.py
> +        if not (customer and order and is_edx_lms_order(order)):
One last thing, you need to read the status and endure its set to sanctioned.

2024-02-01 12:10 UTC, grmartin approved these changes
Pending decision on coverage, proposed to the team...

2024-02-03 00:43 UTC, shafqatfarhan commented on commerce_coordinator/apps/commercetools/views.py
> +    # authentication_classes = [] TODO: Update this with OAuth authentication
No need to explicitly specify authentication_classes in the endpoint as we have `JwtAuthentication` set as default in [REST_FRAMEWORK](https://github.com/edx/commerce-coordinator/blob/main/commerce_coordinator/settings/base.py#L277)

2024-02-03 00:48 UTC, shafqatfarhan commented on commerce_coordinator/apps/commercetools/views.py
> +        customer = client.get_customer_by_id(order.customer_id)
Do we need to catch any API response that raises an error and add an exception log?

2024-02-08 13:43 UTC, merged

2024-02-09 09:48 UTC, shafqatfarhan commented on commerce_coordinator/apps/commercetools/views.py
>          customer = client.get_customer_by_id(order.customer_id)
Suggestion:
- Please move `get_customer_by_id` into try/except block as well
- Change the logger function to exception as we need to be alerted on just exceptions
- Make exception message more meaningful and append API error as well

```
try:
    order = client.get_order_by_id(order_id)
    customer = client.get_customer_by_id(order.customer_id)
except CommercetoolsError as exc:
    logger.exception(f'Error fetching CT Customer or Order with ID "{order_id}". Error: {exc}')
    return Response(status=status.HTTP_404_NOT_FOUND)
```

2024-02-09 09:48 UTC, shafqatfarhan commented on commerce_coordinator/apps/commercetools/views.py
> +        customer = client.get_customer_by_id(order.customer_id)
Suggestion:
- Please move `get_customer_by_id` into try/except block as well
- Change the logger function to exception as we need to be alerted on just exceptions
- Make exception message more meaningful and append API error as well

```
try:
    order = client.get_order_by_id(order_id)
    customer = client.get_customer_by_id(order.customer_id)
except CommercetoolsError as exc:
    logger.exception(f'Error fetching CT Customer or Order with ID "{order_id}". Error: {exc}')
    return Response(status=status.HTTP_404_NOT_FOUND)
```